### ISSUE TITLE
Include normalize

### ISSUE THREAD

**Issue by djfarrelly** [bufferapp/buffer-style#1]
Hey @stevemdixon!
What are your thoughts on including [normalize](https://github.com/necolas/normalize.css/) or some other stylesheet reset?

**Comment by stphndxn** [comment]
Hi @djfarrelly! So sorry I took a little while to get back to you on this! Using Normalize feels really good here -- glad you brought this suggestion up! :smile:

**Comment by djfarrelly** [comment]
Awesome! I can add it to the build :+1:

**Comment by stphndxn** [comment]
Hey again! 😅 Curious if this one has been added? No rush on this one! 😄
