### ISSUE TITLE
Landing Page UI

### ISSUE THREAD

**Issue by stphndxn** [bufferapp/buffer-style#23]
Hey, @docal56, @lorenzvs, @marcanthonyrosa, @Kymorrow!

Lorenz and I had a great sync this morning and we'd love to expand the conversation of how we're thinking of approaching landing page templates in our style guide.

Our design problem here might be that our landing pages can become quite disjointed with perhaps little to no continuity between various landing pages across the app and website.

Our solution to this problem might be that we build various different blocks/layouts, so building and prototyping is crazy fast. 😁 An example of how we're thinking of this can be found over on [blocsapp.com](http://blocsapp.com)!

Curious for thoughts and to perhaps trigger some conversations around this!

**Comment by marcanthonyrosa** [comment]
Hey @stevemdixon, this is so exciting! Love the idea of us improving our time-to-deploy with landing pages. Particularly with landing pages - which are "low risk" ways to test out virtually all positioning elements of Buffer (price points, product offerings, onboarding experiences, value prop, etc) - it feels really great to pursue ways we can be Lean. My two cents, at least!

Can't wait to follow along :) 

cc @docal56 @Kymorrow

**Comment by Kymorrow** [comment]
This feels great @stevemdixon and @lorenzvs! Thank you so much for kicking this off. I completely agree with what @marcanthonyrosa said. It feels great to keep things Lean and improve our time-to-deploy on these. I'm excited to continue the conversation. 😀

**Comment by stphndxn** [comment]
Hey, @nieldlr & @pioul!

With you both having ownership on static pages, I'd love to share an idea with how we might be able to construct our static pages! The idea here might be that have HTML and CSS markup making up "blocks" that we can fit together in any order to create new pages. For example, we might have a hero block at the top of the page, followed by a feature block and a form block; with each block having a single particular purpose.

Happy to roll with whatever feels great here! 😄

**Comment by stphndxn** [comment]
Just circling back to our issues here! 😄 I'm going to close this one up (@nieldlr & @pioul) Niel spoke to me about Niel and I taking ownership of our static pages, which feels great! 👍
