### ISSUE TITLE
Add section for Calendar UI

### ISSUE THREAD

**Issue by stphndxn** [bufferapp/buffer-style#9]
@lorenzvs and I jammed on this today. Super curious on any thoughts on how we might think about cataloguing/categorizing this one!

A few thoughts on this one:
- would each post in the calendar be a "card" object like posts are in the list view?
- if posts in the calendar aren't a card object, is this validation for us to create a brand new UI object?

@lorenzvs made such an awesome observation on how we might better present information in the calendar by applying some of Apple's core design principles used to design for the Apple Watch -- a minimal interface yet filled with such well-placed, valuable information! Super excited to jam on this one with anyone and everyone to help improve this experience for our amazing customers! :heart_eyes: 

cc: @emily-plummer, @KatieLo, @nieldlr

**Comment by lorenzvs** [comment]
@stevemdixon Love the card approach! Especially when the layout inside the card is adaptive to the content. Something I have been exploring for Instagram. :blush: https://buffer.invisionapp.com/d/main/#/console/6578571/146044595/preview

**Comment by stphndxn** [comment]
Woohoo! I love this so much! If it feels great, we might jam within this issue thread on potential designs we might come up with for our new Calendar UI! :smile:

**Comment by stphndxn** [comment]
Hey, friends! I'm going to close this one up and perhaps re-open once we're starting to work on Calendar 2.0! Happy to re-open if that feels great instead! 😁
